### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by karser** [stanlemon/rest-bundle#25]
Is it compatible with Doctrine MongoDB ODM?

**Comment by stanlemon** [comment]
@karser I have not tried it, so I can't really speak to that. In theory it might work, as I have tried to rely primary on features of ```Doctrine\Common``` and not the ```ORM```. Some things I'm not certain about are...
1. JMS Serializer has a Doctrine Object Constructor that I use for PATCH requests, I'm not certain if this works with ODM.  If it does, awesome - if not than PATCH would not work.
2. ```Lemon\RestBundle\Object\Processor``` is probably where problems will exist, but maybe not...  I know right now I trust a method in ```UnitOfWork``` that may need to be refactored for ODM support, as I haven't used ODM on a project recently I can't really speak to that.

I'll leave this issue open so that I can dig into it more in the future. Feel free to investigate and let me know what you find, I'm always happy to have contributions!

Thanks for your interest in ```LemonRestBundle```!

**Comment by stanlemon** [comment]
@karser I spent some time today trying to remove the hard dependencies on the ORM package and use Commons interfaces where appropriate. I think this is going to set the bundle up for Mongo compatibility.  The one major remaining task is a way to control which Doctrine registry is injected into various classes. I believe I am going to add a configuration option for this and manipulate it with a compiler pass. Please let me know if you had an opinion on how this should be done. Once that dependency has been sorted through it should be possible to create a parallel test suite for Doctrine's Mongo ODM.

**Comment by stanlemon** [comment]
@karser There is a working implementation in the mongodb branch, I will be merging this into master soon.

**Comment by stanlemon** [comment]
@karser This functionality is now available in 0.8.0.
